Saving accounts into a txt
claudia-duda/bank-account pull request #1
Opened 2021-07-14 17:54 UTC by claudia-duda

2021-07-14 18:10 UTC, rebeca53 requested changes

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
> +	private FileWriterReader file;
Se for possível, mover a parte de interpretação de input para uma nova classe separada que voce usaria aqui. Assim, se um dia mudar a forma de receber dados, já haverá uma abstração para isso.

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
>  	private Scanner sc;
evite usar abreviações em nomes de variáveis, abreviações são difíceis de lembrar no corpo do código. É interessante usar nomes que "dizem" o que a variável representa

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/entities/Account.java
> +public class Account implements Serializable{
Adicione documentação, ou seja, insira um comentário logo antes da declaração de uma classe ou método descrevendo o que faz.

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/entities/UserData.java
> +		return" Titular = "+fullName+" CPF = "+ CPF +" Data de Nascimento= "+birthday;
Boa ideia sobrescrevendo o método toString!

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
> +			this.view.print("---------Contas cadastradas---------");
Seria interessante declarar os textos utilizados no código em constantes ou em um arquivo separado. Em projetos Android, por exemplo, coloca-se os textos em arquivos xml.

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/operations/FileWriterReader.java
> +		try(BufferedWriter bw = new BufferedWriter(new FileWriter(this.file, true))){
Interessante esse uso do try, não tinha visto ainda :)

2021-07-14 18:10 UTC, rebeca53 commented on Exception/src/operations/FileWriterReader.java
> +public class FileWriterReader {
Sugiro que o nome seja algo tipo, "AccountAdapter" ou "AccountWriterReader" ou outro nome que mostre que essa classe não só le e escreve arquivos, mas especificamente, lê e escreve informações de conta.

2021-07-19 20:19 UTC, claudia-duda commented on Exception/src/aplication/Controller.java
>  			case 3:
tem algum exemplo que eu poderia me basear? acho que não entendi bem

2021-07-20 04:47 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
>  			case 3:
Nesse link tem um exemplo usando Enum e Switch case: https://www.devmedia.com.br/enumeracoes-em-java/25839

2021-07-20 23:32 UTC, claudia-duda commented on Exception/src/aplication/Controller.java
>  			case 3:
usei apenas as constantes ja que no enum ficaria confuso talvez diferenciar a mesma constante pra  duas situações, seria o correto dessa forma?

> public final byte DEPOSIT= 1;
	public final byte CREATE_ACCOUNT= 1;
	public final byte WITHDRAW= 2;
	public final byte REMOVE_ACCOUNT= 2;
	public final byte ACCESS_ACCOUNT= 3;
	public final byte USER_DATA= 3;
	public final byte LIST_ACCOUNTS= 4;
	public final byte BANK_MENU= 0;

2021-07-20 23:33 UTC, claudia-duda commented on Exception/src/aplication/Controller.java
> +	private FileWriterReader file;
eu colocaria isso tentando adicionar algo de interface ? 
no caso eu tiraria todas as leituras de input e recebia no parametro dos métodos do controller?

2021-07-21 00:15 UTC, claudia-duda commented on Exception/src/aplication/Controller.java
> +			this.view.print("---------Contas cadastradas---------");
vou tenta implementa isso quando eu fazer a separação do interpretador dos inputs

2021-07-21 00:18 UTC, claudia-duda commented
Terminando a documentação, eu tento subir as alterações ja feitas, em seguida sigo para o interpretador do input e as constantes em um arquivo separado

2021-07-22 20:19 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
>  			case 3:
Sim, tem razão. Inclusive, você poderia usar uma variável para cada situação. Por exemplo:

// Values of accountOperationChoice
public final byte BANK_MENU= 0;
public final byte DEPOSIT= 1;
public final byte WITHDRAW= 2;
public final byte SHOW_USER_DATA= 3;
// operation over account selected by user
private Byte accountOperationChoice = 1;

public final byte CREATE_ACCOUNT= 1;
public final byte REMOVE_ACCOUNT= 2;
public final byte ACCESS_ACCOUNT= 3;
public final byte LIST_ACCOUNTS= 4;
// bank menu option selected by user
private Byte bankMenuOptionChoice = 1;

2021-07-22 21:04 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
> +	private FileWriterReader file;
Isso tudo é só sugestão, o código já tá massa, mas vamos lá:

O jeito mais simples seria apenas encapsular o uso do scanner em métodos. Por exemplo, inputValue(), inputAccount(), requestChoice(). 

Depois, você percebendo que os métodos estão relacionados, pode agrupá-los em uma classe separada. Considerando que você está instanciando a view no controller mesmo, pode instanciar a classe de UserInput() (ou outro nome que você escolher) da mesma forma. Daí, você usaria os métodos da forma abaixo. Isso faz com o que o código fique mais fácil de entender, além de separar funcionalidades.

Por último, poderia declarar a interface e fazer sua classe implementar a interface.

Pseudo código:
Classe Input teria métodos
Int inputValue() {
	return sc.nextInt();
}
Account inputAccount() – called in createAccount
Byte inputChoice()

Na Controller, o código ficaria mais limpo:
run() {
	while (choice !=0) {
		//request option
view.options()
choice = inputChoice()

// execute option
op = accountChoices(choice)

if (op != null) {
	// request data
	view.print()
	value = inputValue()
	
// execute operation
op.action()
account.balance()
…
		}
	}
}

accountsControl() {
	view.accountMenu();
	choice = inputChoice();
	switch(choice) {
		case 1: createAccount()
		case 2: view.print(), inputValue(), operation()
		case 3: view.print(), inputValue(), operation()
	}
	}

2021-07-25 22:39 UTC, closed without merging

2021-08-05 21:48 UTC, rebeca53 commented on Exception/.gitignore
> +.classpath
Boa! Temos um gitignore agora!

2021-08-05 21:50 UTC, rebeca53 commented on Exception/src/aplication/Controller.java
> +		String CPF= "defal";
É "defal" mesmo?